name: "dropwizard-ci-pipeline"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build -x test
      - name: Run tests
        run: ./gradlew test

  deploy:
    needs: build-and-test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Remove .git to prevent access issue
        run: |
          echo "Exclude .git..."
          rm -rf .git
          shell: bash
      - name: Copy toy-drop to Cybera
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "."
          target: "~/prod"
          overwrite: true
      - name: Restart All Instances On Cybera
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            set -e
            cd ~/prod
            docker compose down
            docker compose up --build -d